"""Shared constants for the GoldRush2 simulator."""

GRID_SIZE = 17
MAX_NPCS = 7
MOVE_BUDGET = 6
PLAYER_UNIT_COUNT = 2
PLAYER_IDS = (1, 2)

ACTION_UP = 0
ACTION_DOWN = 1
ACTION_LEFT = 2
ACTION_RIGHT = 3
ACTION_STAY = 4
VALID_ACTIONS = frozenset({ACTION_UP, ACTION_DOWN, ACTION_LEFT, ACTION_RIGHT, ACTION_STAY})
ACTION_DELTAS = {
    ACTION_UP: (-1, 0),
    ACTION_DOWN: (1, 0),
    ACTION_LEFT: (0, -1),
    ACTION_RIGHT: (0, 1),
    ACTION_STAY: (0, 0),
}

GRID_FOG = -5
GRID_BOMB = -3
GRID_OBSTACLE = -1
GRID_EMPTY = 0

STATIC_EMPTY = 0
STATIC_OBSTACLE = 1
STATIC_SPECIAL_NON_BLOCKING = 2

DEFAULT_VISION_RADIUS = 2
VISION_RADIUS_BY_VP = {
    0: DEFAULT_VISION_RADIUS,
    1: 3,
    2: 4,
}
VISION_COST_BY_VP = {
    0: 0,
    1: 2,
    2: 3,
}

PICKUP_NUMERATOR = 65
PICKUP_DENOMINATOR = 100
BOMB_LOSS_NUMERATOR = 10
BOMB_LOSS_DENOMINATOR = 100
TRAMPLE_LOSS_NUMERATOR = 5
TRAMPLE_LOSS_DENOMINATOR = 100
TRAMPLE_NPC_THRESHOLD = 3

ROUND_COUNT = 500
SNAPSHOT_PERIOD = 5
REGION_COUNT = 5

